import pyglet

pyglet.resource.path = ["@game.resources_folder"]
pyglet.resource.reindex()

BG = pyglet.resource.image("BG.png")
BG2 = pyglet.resource.image("BG2.png")
bull1 = pyglet.resource.image("bull1.png")
bull2 = pyglet.resource.image("bull2.png")
Freeze = pyglet.resource.image("Freeze.png")
GBG = pyglet.resource.image("GBG.png")
GchooseB = pyglet.resource.image("GchooseB.png")
GchooseB1 = pyglet.resource.image("GchooseB1.png")
GchooseS = pyglet.resource.image("GchooseS.png")
GchooseS1 = pyglet.resource.image("GchooseS1.png")
GN = pyglet.resource.image("GN.png")
GNp = pyglet.resource.image("GNp.png")
Hmeteorji = pyglet.resource.image("Hmeteorji.png")
Hmetki = pyglet.resource.image("Hmetki.png")
LHE = pyglet.resource.image("LHE.png")
meteor1 = pyglet.resource.image("meteor1.png")
meteor2 = pyglet.resource.image("meteor2.png")
metki = pyglet.resource.image("metki.png")
Pmetki = pyglet.resource.image("Pmetki.png")
pu1 = pyglet.resource.image("pu1.png")
pu2 = pyglet.resource.image("pu2.png")
raketa1 = pyglet.resource.image("raketa1.png")
raketa2 = pyglet.resource.image("raketa2.png")
Shield = pyglet.resource.image("Shield.png")
slow = pyglet.resource.image("slow.png")
speed = pyglet.resource.image("speed.png")
